title: "KALA SOLOTHURN 2028"
description: "Werde Teil des KaLa-Teams!"
theme: jekyll-theme-cayman
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false

include:
  - _includes

sass:
  style: compressed
